api:
  build: ../api/
  container_name: api
  environment:
    - SERVICE_HOST=0.0.0.0
    - API_PORT=10000
  ports:
    - 10000:20000
base:
  build: ../base/
  container_name: base
  environment:
    - SERVICE_HOST=0.0.0.0
    - API_PORT=10000
user_service:
  build: ../user/
  container_name: user_service
  environment:
    - SERVICE_HOST=0.0.0.0
    - API_PORT=10000
    
company_service:
  build: ../company/
  container_name: company_service
  environment:
    - SERVICE_HOST=0.0.0.0
    - API_PORT=10000